backend:
name: git-gateway
branch: main # o master según tu repo
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: es
publish_mode: simple
site_url: "/"

collections:
- name: "photos"
label: "Fotos"
delete: true
editor:
preview: false
files:
- name: "photosData"
label: "Listado de fotos"
file: "data/photos.json"
format: json
fields:
- label: "Fotos"
name: ""
widget: list
fields:
- {label: "ID", name: "id", widget: "uuid"}
- {label: "Título", name: "title", widget: "string"}
- {label: "Imagen", name: "image", widget: "image"}
- {label: "Etiquetas", name: "tags", widget: "list", default: []}
- {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD"}